---

- name: Lord Installation
  hosts: localhost
  vars: 
    vendors_directory_raw: "{{ ansible_env.PWD }}/../Vendors"
    vendors_directory: "{{ vendors_directory_raw | realpath }}"

  tasks:
    - debug: msg={{ vendors_directory }}

    - name: Installing the core of Lord.ansible
      git: repo=https://github.com/elmar-hinz/OSX.Me.git dest={{ vendors_directory }}/Lord/Me

